### PR TITLE
Fix-prop-float

### LINKED ISSUE #13: Champollion not decompiling floats correctly.
Posted on Nexus: https://www.nexusmods.com/skyrimspecialedition/mods/75248?tab=bugs&BH=0

> I observed the new Champollion that you added isn't decompiling floats correctly on my end. They are decompiled as integers in the scripts and throw errors soon after in the process as the papyrus compiler tries to build.
> 
> I fixed it by switching out the Champollion with another in nexus. Namely this one: https://www.nexusmods.com/skyrim/mods/35307
> 
> EDIT: I couldnt obtain the error output because the compiler never crashes and indefinitely hangs accumulating memory in the background.

### PR DESCRIPTION
**Pull request by nikitalita**
float initalizers without `.0` at the end were rejected by PCompiler

Fixes #13

### CODE REVIEW

File: Decompiler/PscCoder.cpp [hunk 1]
```diff
@@ -348,7 +348,12 @@ void Decompiler::PscCoder::writeProperty(int i, const Pex::Property& prop, const
 
         auto initialValue = var->getDefaultValue();
         if (initialValue.getType() != Pex::ValueType::None)
+        {
             stream << " = " << initialValue.toString();
```
Comment (Orvid) [inline Decompiler/PscCoder.cpp]: It would probably be better to fix `.toString()` to return with the right trailing decimals. I believe it should just be removing these lines, which appear to exist to remove the trailing `.0`:

https://github.com/Orvid/Champollion/blob/master/Pex/Value.cpp#L295-L304

Comment (nikitalita) [reply Decompiler/PscCoder.cpp]: derp, of course. thank you.
